### ISSUE TITLE
The lingualearn logo should be consistent

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/LinguaLearn#12]
The lingualearn logo at the top right of the screen should be the same across pages - it should be clicked to go to the homepage. Any back button shouldn't be incorporated into that logo but should be a completely separate thing.

**Comment by jacob-macleod** [comment]
@nathan-a-macleod thanks for adding this issue. What do you mean by this exactly? Should I create a separate back button on the top menu? Where should I put it?

**Comment by nathan-a-macleod** [comment]
Yep so currently, the logo is normally just a logo, however on some pages it becomes a back button.
Instead, the logo should never be a back button. If that page needs a back button it should be added separately to the logo

**Comment by jacob-macleod** [comment]
Ok, thanks

**Comment by jacob-macleod** [comment]
I have now fixed this
